name: "Creating the CICD Demo for job"

on:
    push:
        branches:
            - main
            - master
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps: 
            - name: "Setting Github Actions"
              uses: actions/setup-node@v5
              with:
                node-version: '16'

            - name: "Checking Version"
              run: node --version

             
            - name: Fetch Full History
              uses: actions/checkout@v4
              with:
                 fetch-depth: 0
            - name: "Listing before dependancies installign"
              run: ls
            - name: "Installing npm"
              run: npm install
            - name: "After installing the list will be "
              run: ls